### ISSUE TITLE
Make fake.cmd and fake.sh boostrap fake

### ISSUE THREAD

**Issue by cmeeren** [MangelMaxime/fulma-demo#15]
Could it be a good idea to make fake.cmd and fake.sh boostrap fake? I've seen this in numerous repos and have used it in https://github.com/elmish/Elmish.WPF.

fake.cmd:

```cmd
SET TOOL_PATH=.fake

IF NOT EXIST "%TOOL_PATH%\fake.exe" (
  dotnet tool install fake-cli --tool-path ./%TOOL_PATH%
)

"%TOOL_PATH%/fake.exe" %*
```

fake.sh:

```bash
#!/usr/bin/env bash

set -eu
set -o pipefail

# liberated from https://stackoverflow.com/a/18443300/433393
realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}

TOOL_PATH=$(realpath .fake)
FAKE="$TOOL_PATH"/fake

if ! [ -e "$FAKE" ]
then
  dotnet tool install fake-cli --tool-path "$TOOL_PATH"
fi
"$FAKE" "$@"
```

**Comment by MangelMaxime** [comment]
Fake is already being bootstrap by using the `build.proj`. Also by using `build.proj` I can use paket to lock the version.

I don't see a benefit of using `dotnet tool ` as it will always dowload the latest version of `FAKE` or I would need to manage the version by hand my self.

**Comment by cmeeren** [comment]
Thanks for the clarification!

If the build.proj file had contained a comment like this, I would probably have understood it and not felt the need to ask:

> This project file, together with paket.references and the fake.cmd and fake.sh scripts, is used to bootstrap Fable and Fake using Paket to lock the version.

You might consider updating the comment, if you want.

**Comment by MangelMaxime** [comment]
I will accept a PR for adding this information :)
