### ISSUE TITLE
Demo needs a "new question" button

### ISSUE THREAD

**Issue by rmunn** [MangelMaxime/fulma-demo#2]
The Fulma demo looks really great! I'm looking forward to showing it off to my colleagues and showing them how little code is needed for something like this. It feels just a little incomplete, though: if you can answer a question, but not ask any new questions, it feels like the demo is only half finished. A simple "Ask a new question" button would make the demo feel more like a complete demo, and I think it wouldn't take all that much effort to add.

**Comment by MangelMaxime** [comment]
So I just can't be a bit lazy ? :)

As always, it's a good suggestion I will add it, thanks for proposing.

**Comment by MangelMaxime** [comment]
Sorry for the delay @rmunn I was in release period at work :)

I published a new version of Fulma-demo allowing to ask new questions. I will also add pagination support tracked here https://github.com/MangelMaxime/fulma-demo/issues/3
