### ISSUE TITLE
WebSocket connection to 'ws://localhost:8000/socketcluster/

### ISSUE THREAD

**Issue by thelazydogsback** [MangelMaxime/fulma-demo#25]
I get the following errors in the debug console when running the demo.
AFAICT the demo seems to be working, but maybe missing some functionality specific to websockets.

thanks

==========================

SocketProtocolError WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Failed to load resource: the server responded with a status of 404 (Not Found) [http://localhost:8080/img/favicon-32x32.ico]   (and 16x16)

**Comment by MangelMaxime** [comment]
What did you try to do with WebSockets? 

By default, the template doesn't support WebSockets and also the server is accessible from 8080, not 8000.

**Comment by MangelMaxime** [comment]
> By default, the template doesn't support WebSockets

At least not out of the box, if something special is needed for them

**Comment by thelazydogsback** [comment]
I didn't "try" and do anything -- I just cloned the repo and ran as-is...

**Comment by thelazydogsback** [comment]
But, as a side note, that would be a great addition to the sample -- I have three upcoming apps and any of them would need websockets.

**Comment by MangelMaxime** [comment]
Do you have the [redux debugger](https://github.com/zalmoxisus/redux-devtools-extension) installed in your browser?

Because the template is [using it](https://github.com/MangelMaxime/fulma-demo/blob/master/src/App.fs#L90). And so, if you don't have it installed it will complain and put a lot of connection failed.

**Comment by MangelMaxime** [comment]
I am closing this issue because I am almost certain it is because you don't have redux debugger installed.

Please feel free to re-open the issue if needed :)

**Comment by halcwb** [comment]
@MangelMaxime ran into the same issue, having no clue where to look for. Is this problem documented anywhere other than hidden in this issue?

**Comment by MangelMaxime** [comment]
@halcwb 

In theory, I gave the solution in the discussion.

> Do you have the [redux debugger](https://github.com/zalmoxisus/redux-devtools-extension) installed in your browser?
>
> Because the template is [using it](https://github.com/MangelMaxime/fulma-demo/blob/26eb260e5c742488bcf790a9517df0640e39327d/src/App.fs#L92-L94). And so, if you don't have it installed it will complain and put a lot of connection failed.

Either install Redux debugger (via web extension) or remove it from the application.
