### ISSUE TITLE
Is the build.proj file needed?

### ISSUE THREAD

**Issue by mastoj** [MangelMaxime/fulma-demo#34]
I tried running `fake build` and it seems to be working, so can the `build.proj` be deleted together with `fake.sh` and instead rely on `fake` being installed globally?

**Comment by mastoj** [comment]
Or isn't it possible to install local tools now?

**Comment by MangelMaxime** [comment]
It's working because you have FAKE installed globally but I don't like global tools because you can't manage their version per project etc.

I am ok for using local tools, it's what I started to do in my other projects.

**Comment by MangelMaxime** [comment]
I reworked the project setup to use local tools from dotnet.
