### ISSUE TITLE
webpack.config.js - Hot-Reload not working on Webpack 5

### ISSUE THREAD

**Issue by pkese** [MangelMaxime/fulma-demo#45]
https://github.com/MangelMaxime/fulma-demo/blob/3d7ad93234364bc40701d5b288e8ed3de12522be/webpack.config.js#L54

I've just been debugging why Webpack 5 upgrade breaks Hot-Reloading and found out that the culprit was this part of `webpack.config.js`:

```js
    // In development, have two different entries to speed up hot reloading.
    // In production, have a single entry but use mini-css-extract-plugin to move the styles to a separate file.
    entry: isProduction ? {
        app: [CONFIG.fsharpEntry, CONFIG.cssEntry]
      } : {
            app: [CONFIG.fsharpEntry],
            style: [CONFIG.cssEntry]
        },
```

After changing this to just:

```js
    entry: {
        app: [CONFIG.fsharpEntry, CONFIG.cssEntry]
      }
```

... Hot-Reload started working again.

I felt like sharing this - it might save someone some time.

**Comment by pkese** [comment]
Also running fable should be changed from

```dotnet fable watch src --run webpack-dev-server```
to
```dotnet fable watch src --run webpack serve```

And 

```var isProduction = !process.argv.find(v => v.indexOf('webpack-dev-server') !== -1);```
to
```var isProduction = process.argv.indexOf('serve') === -1;```

**Comment by MangelMaxime** [comment]
@pkese Thank you for investigating the issue and for the fixes :)

**Comment by pkese** [comment]
No worries and sorry for polluting the ticket tracker with this semi-relevant issue.  
I was wondering if this was is a proper repository to comment about this, so   
I guess I commented here just because #43 was exposed on Fable blog thus pointing to this repo.

Oh, and since I already caught your attention, may I seize the opportunity to thank you @MangelMaxime for all your contributions to the F# and Fable ecosystem. I appreciate your work very much.

**Comment by MangelMaxime** [comment]
Thank you for the kind words @pkese it really helps to read sometimes :)

The master branch has been upgraded to Fable 3 and Webpack 5.
