### ISSUE TITLE
Can't run Fable 2 branch

### ISSUE THREAD

**Issue by MangelMaxime** [MangelMaxime/fulma-demo#6]
@matthid @alfonsogarciacaro

When I try to run Fable from FAKE, I get this error:

```
Version for package `dotnet-fable` could not be resolved.
```

If I do `dotnet fable webpack-dev-server` manually it's working. Any ideas ?

The code is on `fable2` branch https://github.com/MangelMaxime/fulma-demo/pull/5

* Operating system: **Darwin**
* Arch: **x64**
* VSCode: **1.24.1**
* Runtime: **netcore**
* Dotnet version: **2.1.301** and **2.1.300**

**Comment by matthid** [comment]
Your best bet is to capture both calls (from command line and fake) via procexp or process monitor and compare:

- working directory
- path to dotnet.exe
- environment variables
- (arguments?)

I guess there is a difference somewhere.

**Comment by MangelMaxime** [comment]
Hum, ok seems like I understand the difference.

From shell:

```
> dotnet --version
2.1.301
> which dotnet
/usr/local/share/dotnet/dotnet
```

From FAKE:
```
/Users/maximemangel/.dotnet/dotnet  --version
2.1.4
```

**Comment by MangelMaxime** [comment]
I deleted the `/Users/maximemangel/.dotnet/dotnet` I don't know how it has been created. Will see if it came back later. 

Thank you @matthid

**Comment by matthid** [comment]
Yes I hope we can improve the situation a bit with https://github.com/fsharp/FAKE/pull/1963
At least FAKE will respect PATH (in case it contains the correct version).

Next release should contain this.

**Comment by alfonsogarciacaro** [comment]
What I've done in other projects to ensure CLI and FAKE use same version is add the global.json file and then read the version in the global.json at the beginning of the FAKE script. Isn't there a helper now to do that?

**Comment by MangelMaxime** [comment]
Problem with the `globaj.json`, is when you work on different project with different version. Then each time you switch you need to re-download/re-install dotnet core. Taking way to long ... :)

**Comment by alfonsogarciacaro** [comment]
But you can have multiple dotnet SDK versions installed in your system and global.json will pick the right one.

**Comment by MangelMaxime** [comment]
Then the problem to fix is to install a new one whitout removing old ones I guess. 

Because, today if I switch to project using `2.1.4` then another using `2.1.300` and go back to `2.1.4`, I will need to download again `2.1.4` and re-install it which takes severals minutes.

**Comment by MangelMaxime** [comment]
I do agree there is something to improve on this subject :)

Just because of how the situation is today, I don't want to wait 5 minutes each time I switch from one project to another :) If I manage, the project I could "simply" update the expected version. But when working with others project it's not the case :)

**Comment by matthid** [comment]
Before running around changing everything you can wait or try the staging version of fake and check if it fixes the problem

**Comment by MangelMaxime** [comment]
Sure 😊that’s my plan
