### ISSUE TITLE
Paket.exe not working

### ISSUE THREAD

**Issue by selketjah** [MangelMaxime/fulma-demo#8]
I think it is still an old version of paket.exe because I keep getting this error:

> The request was aborted: Could not create SSL/TLS secure channel. (Github - cached)

**Fix:**
When I downloaded latest version from repo and replaced it, it worked fine.

**Comment by MangelMaxime** [comment]
You need to update the paket.bootstrapper.exe.

1. Go to paket repo
2. Download `paket.bootstrapper.exe` from the release tab
3. Delete all the content in `.paket` folder
4. Paste the download `paket.bootstrapper.exe`
5. Enjoy
